spotlight/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^spotlight_server/', include('spotlight_server.urls', namespace='spotlight_server')),
    url(r'^admin/', admin.site.urls),
]

spotlight_server/urls.py
from django.conf.urls import url

from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^tweets', views.tweet_index, name='tweet_list'),
    url(r'^report', views.report, name='report'),
    url(r'^users', views.user_index, name='user_list'),
    url(r'^user/', views.user_confirmation, name='user_confirmation'),
    url(r'^version', views.version_check, name='version_check'),
    url(r'^users/csv', views.user_csv, name='user_csv'),
    url(r'^tweets/csv', views.tweet_csv, name='tweet_csv'),
    url(r'^login/', auth_views.login, {'template_name': 'login.html'}),

]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"ja-jp" }}">
<head>
<meta charset="UTF-8">
<title>{% block title %}spotlight_server{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<style>
    h3 {
        padding: 0.7em 0 0.3em 1em;
    }
</style>
<link rel="shortcut icon" href="{{ STATICFILES_DIRS }}/static/favicon.ico" type="image/png">
{% block extrahead %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'spotlight_server:index' %}">Spotlight Server</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'spotlight_server:index' %}">Home</a></li>
            <li><a href="{% url 'spotlight_server:user_list' %}">登録者リスト</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

  <div class="container">
    {% block body %}
      {{ body }}
    {% endblock %}
  </div>

</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block extrahead %}
<style>
table {
  margin-top: 10px;
}
</style>
{% endblock %}

{% block body %}
    <h3 class="page-header">管理ページ</h3>
    <h4>
        <a href="{% url 'spotlight_server:user_list' %}" class="btn btn-default btn-sm">登録者リスト</a>
    </h4>
{% endblock %}

templates/login.html
{% extends "admin/base.html" %}
{% load widget_tweaks %}

{% block content %}

<!-- ログイン失敗時には、ここでエラーメッセージを表示する -->
{% if form.errors %}
<p xmlns="http://www.w3.org/1999/html">なんかおかしいです</p>
{% endif %}

<form class="form-signin" method="post" action="{% url 'spotlight_server:index' %}">
    {% csrf_token %}
    <h2>Sign in</h2>

    <hr />

    <div class="form-group">
        <label for="{{ form.username.id_for_label }}" class="sr-only">{{ form.username.label }}</label>
        {% render_field form.username class="form-control" placeholder=form.username.label %}
    </div>
    <div class="form-group">
        <label for="{{ form.password.id_for_label }}" class="sr-only">{{ form.password.label }}</label>
        {% render_field form.password class="form-control" placeholder=form.password.label %}
    </div>

    <button type="submit" value="Sign in"> </button>
</form>
{% endblock %}

templates/tweet.html
{% extends "base.html" %}

{% block extrahead %}
<style>
table {
  margin-top: 10px;
}
</style>
{% endblock %}

{% block body %}
    <h3 class="page-header">Tweet一覧</h3>
    <h4> <a href="{% url 'spotlight_server:tweet_csv' %}" class="btn btn-default btn-sm">CSV</a></h4>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
            <th>ID</th>
            <th>Retweet count</th>
            <th>Favorite count</th>
            <th>Text</th>
            <th>Created at</th>
            <th>Good</th>
            <th>Bad</th>
        </tr>
      </thead>
      <tbody>
        {% for tweet in tweets %}
          <tr>
            <td>{{ tweet.id }}</td>
            <td>{{ tweet.retweet_count }}</td>
            <td>{{ tweet.favorite_count }}</td>
            <td>{{ tweet.text }}</td>
            <td>{{ tweet.created_at }}</td>
            <td>{{ tweet.good }}</td>
            <td>{{ tweet.bad }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </form>
    <div class="pagination">
        <span class="step-links">
            {% if tweets.has_previous %}
                <a href="?id={{ id }}&page={{ tweets.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ tweets.number }} of {{ tweets.paginator.num_pages }}.
            </span>

            {% if tweets.has_next %}
                <a href="?id={{ id }}&page={{ tweets.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

templates/user.html
{% extends "base.html" %}

{% block extrahead %}
<style>
table {
  margin-top: 10px;
}
</style>
{% endblock %}

{% block body %}
    <h3 class="page-header">登録者リスト</h3>
    <h4> <a href="{% url 'spotlight_server:user_csv' %}" class="btn btn-default btn-sm">CSV</a></h4>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
            <th>Profile image </th>
            <th>ID</th>
            <th>Screen name</th>
            <th>Name</th>
            <th>Followers count</th>
            <th>Friends count</th>
            <th>Location</th>
            <th>Description</th>
            <th>Rank</th>
            <th>Created at</th>
            <th>Tweet</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
          <tr>
            <td><img src="https://pbs.twimg.com/profile_images/771227016968318976/IGxONPRz.jpg" width="50" height="50"></td>
{#            <td><img src="{{ user.profile_image_url }}" width="50" height="50"></td>#}
            <td>{{ user.id }}</td>
            <td>{{ user.screen_name }}</td>
            <td>{{ user.name }}</td>
            <td>{{ user.followers_count }}</td>
            <td>{{ user.friends_count }}</td>
            <td>{{ user.location }}</td>
            <td>{{ user.description }}</td>
            <td>{{ user.rank }}</td>
            <td>{{ user.created_at }}</td>
            <td>
                <a href="/spotlight_server/tweets/?id={{ user.id }}" class="btn btn-default btn-sm">一覧</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </form>
    <div class="pagination">
        <span class="step-links">
            {% if users.has_previous %}
                <a href="?page={{ users.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ users.number }} of {{ users.paginator.num_pages }}.
            </span>

            {% if users.has_next %}
                <a href="?page={{ users.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
{% endblock %}